linters-settings:
  custom:
    loglinter:
      path: ./custom_linter.so
      description: "Линтер для проверки логов"
      original-url: github.com/malinavarvara/linter

linters:
  disable-all: true
  enable:
    - loglinter

issues:
  # Отключаем лимиты, чтобы увидеть все найденные ошибки в тестовом файле
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false